// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk0VsM-azETROyfQb6aefTBkz4KayV3lI',
    appId: '1:442738042363:web:71550dd6864410d7f2d75e',
    messagingSenderId: '442738042363',
    projectId: 'fir-test-f3ae9',
    authDomain: 'fir-test-f3ae9.firebaseapp.com',
    databaseURL: 'https://fir-test-f3ae9.firebaseio.com',
    storageBucket: 'fir-test-f3ae9.appspot.com',
    measurementId: 'G-RCN90JW750',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5uRwXbIJXaH7mZLslm3hWAHtIYDD-72M',
    appId: '1:442738042363:android:e4c80077d49cb551f2d75e',
    messagingSenderId: '442738042363',
    projectId: 'fir-test-f3ae9',
    databaseURL: 'https://fir-test-f3ae9.firebaseio.com',
    storageBucket: 'fir-test-f3ae9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANvMzANM9yT0XRiuWuFswb3pBIcAqK9aE',
    appId: '1:442738042363:ios:649239c60f3f1351f2d75e',
    messagingSenderId: '442738042363',
    projectId: 'fir-test-f3ae9',
    databaseURL: 'https://fir-test-f3ae9.firebaseio.com',
    storageBucket: 'fir-test-f3ae9.appspot.com',
    androidClientId:
        '442738042363-r8dg685fmfve32hiqgqdao83rptsmg0b.apps.googleusercontent.com',
    iosClientId:
        '442738042363-gsuv84bavg8a35hjgeem4q97gjqnr56q.apps.googleusercontent.com',
    iosBundleId: 'com.example.notification',
  );
}
